import type {
  PublicAnnouncement,
  PublicCalendarEvent,
  PublicEventType,
  PublicProject,
  PublicSemester,
} from "@/features/events/public-types";

export const demoSemester: PublicSemester = {
  id: "demo-semester-2026-2",
  name: "2026.2",
  startsOn: "2026-07-01",
  endsOn: "2026-12-20",
};

export const demoProjects: PublicProject[] = [
  { id: "demo-rover", name: "Rover", slug: "rover" },
  { id: "demo-vsss", name: "VSSS", slug: "vsss" },
  { id: "demo-ssl-el", name: "SSL-EL", slug: "ssl-el" },
  {
    id: "demo-seguidor-de-linha",
    name: "Seguidor de Linha",
    slug: "seguidor-de-linha",
  },
  {
    id: "demo-robo-de-combate",
    name: "Robô de Combate",
    slug: "robo-de-combate",
  },
];

export const demoEventTypes: PublicEventType[] = [
  {
    slug: "general-meeting",
    label: "Reunião geral",
    colorToken: "brand-red",
    iconKey: "users",
    sortOrder: 10,
  },
  {
    slug: "deadline",
    label: "Prazo",
    colorToken: "brand-amber",
    iconKey: "clock-3",
    sortOrder: 20,
  },
  {
    slug: "competition",
    label: "Competição",
    colorToken: "brand-red",
    iconKey: "trophy",
    sortOrder: 30,
  },
  {
    slug: "milestone",
    label: "Marco importante",
    colorToken: "text-primary",
    iconKey: "flag",
    sortOrder: 40,
  },
];

export const demoEvents: PublicCalendarEvent[] = [
  {
    id: "demo-event-1",
    title: "Reunião geral",
    start: "2026-07-28T19:00:00-03:00",
    end: "2026-07-28T20:30:00-03:00",
    allDay: false,
    type: "general-meeting",
    status: "confirmed",
    projects: [],
    location: "Sala TITANS",
    meetingUrl: null,
    responsible: "Diretoria",
    description: "Alinhamento de abertura do semestre.",
    links: [
      {
        id: "demo-link-1",
        label: "Pauta da reunião",
        url: "https://example.com/pauta-reuniao",
        sortOrder: 10,
      },
    ],
    isImportant: true,
    changeNotice: null,
    seriesId: null,
  },
  {
    id: "demo-event-2",
    title: "Entrega de documentação",
    start: "2026-07-31T00:00:00-03:00",
    end: "2026-08-01",
    allDay: true,
    type: "deadline",
    status: "pending",
    projects: [demoProjects[0], demoProjects[1]],
    location: null,
    meetingUrl: "https://meet.google.com/titans-demo",
    responsible: "Líderes de projeto",
    description: "Prazo interno para revisão dos materiais.",
    links: [],
    isImportant: false,
    changeNotice: null,
    seriesId: null,
  },
  {
    id: "demo-event-3",
    title: "Janela de competição",
    start: "2026-08-13T00:00:00-03:00",
    end: "2026-08-16",
    allDay: true,
    type: "competition",
    status: "changed",
    projects: [demoProjects[0]],
    location: "Laboratório",
    meetingUrl: null,
    responsible: "Equipe Rover",
    description: "Período reservado para preparação e testes.",
    links: [],
    isImportant: true,
    changeNotice: "Local atualizado: Laboratório",
    seriesId: null,
  },
  {
    id: "demo-event-4",
    title: "Marco de integração",
    start: "2026-08-20T18:00:00-03:00",
    end: "2026-08-20T19:00:00-03:00",
    allDay: false,
    type: "milestone",
    status: "completed",
    projects: [demoProjects[2]],
    location: null,
    meetingUrl: null,
    responsible: null,
    description: null,
    links: [],
    isImportant: false,
    changeNotice: null,
    seriesId: null,
  },
  {
    id: "demo-event-5",
    title: "Revisão cancelada",
    start: "2026-08-26T17:00:00-03:00",
    end: "2026-08-26T18:00:00-03:00",
    allDay: false,
    type: "general-meeting",
    status: "cancelled",
    projects: [],
    location: null,
    meetingUrl: null,
    responsible: null,
    description: "Mantido visível para evitar dúvidas.",
    links: [],
    isImportant: false,
    changeNotice: null,
    seriesId: null,
  },
];

export const demoAnnouncements: PublicAnnouncement[] = [
  {
    id: "demo-announcement-1",
    title: "Cronograma em modo de demonstração",
    body: "Os dados serão substituídos pelo Supabase quando o ambiente local estiver disponível.",
    severity: "info",
    startsAt: "2026-07-01T00:00:00-03:00",
    endsAt: null,
    relatedEventId: "demo-event-1",
  },
];
